/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#111416",
        surface: "#111416",
        "surface-dim": "#111416",
        "surface-container-lowest": "#0c0f10",
        "surface-container-low": "#191c1e",
        "surface-container": "#1d2022",
        "surface-container-high": "#272a2c",
        "surface-container-highest": "#323537",
        "surface-variant": "#323537",
        "surface-bright": "#373a3c",
        "on-surface": "#e1e2e5",
        "on-surface-variant": "#c4c7c8",
        "on-background": "#e1e2e5",
        outline: "#8d9193",
        "outline-variant": "#434749",
        primary: "#ffb692",
        "primary-container": "#5a2200",
        "primary-fixed": "#ffdbcb",
        "primary-fixed-dim": "#ffb692",
        "on-primary": "#562000",
        "on-primary-container": "#ff700f",
        "on-primary-fixed": "#341100",
        "on-primary-fixed-variant": "#7a3000",
        "inverse-primary": "#9f4200",
        secondary: "#8adb4d",
        "secondary-container": "#56a315",
        "secondary-fixed": "#a5f866",
        "secondary-fixed-dim": "#8adb4d",
        "on-secondary": "#183800",
        "on-secondary-container": "#143000",
        "on-secondary-fixed": "#0b2000",
        "on-secondary-fixed-variant": "#255100",
        tertiary: "#9dcafd",
        "tertiary-container": "#00355a",
        "tertiary-fixed": "#d0e4ff",
        "tertiary-fixed-dim": "#9dcafd",
        "on-tertiary": "#003256",
        "on-tertiary-container": "#729fcf",
        "on-tertiary-fixed": "#001d34",
        "on-tertiary-fixed-variant": "#134975",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2e5",
        "inverse-on-surface": "#2e3133",
        "surface-tint": "#ffb692",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Work Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
