# Generated by Django 4.2.16 on 2026-04-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
