# Generated by Django 4.2.16 on 2026-04-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_profile_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
    ]
