# Generated by Django 4.2.30 on 2026-04-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_user_chat_turn_count_user_last_reset_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_turn_count',
        ),
    ]
