# Generated by Django 4.2.16 on 2026-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
