# Generated by Django 4.2.16 on 2026-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0002_resume_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_initial_draft',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
