# Generated by Django 4.2.30 on 2026-04-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate_app', '0004_set_calvin_pro_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='chat_turn_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
